// this algorithm is generated by Codex

import Decimal from "decimal.js";

const MODEL_CONFIGS = {
  CY: {
    intervalDigits: 13,
    maxContinuedFractionDepth: 21,
    maxComponentDigits: 8,
    maxTotalFractionDigits: 9,
  },
  EY: {
    intervalDigits: 17,
    maxContinuedFractionDepth: 29,
    maxComponentDigits: 8,
    maxTotalFractionDigits: 9,
  },
};

function absBigInt(value) {
  return value < 0n ? -value : value;
}

function gcd(a, b) {
  a = absBigInt(a);
  b = absBigInt(b);

  while (b !== 0n) {
    [a, b] = [b, a % b];
  }

  return a;
}

function rational(numerator, denominator = 1n) {
  if (denominator === 0n) {
    throw new RangeError("zero denominator");
  }

  if (denominator < 0n) {
    numerator = -numerator;
    denominator = -denominator;
  }

  const divisor = gcd(numerator, denominator);

  return {
    numerator: numerator / divisor,
    denominator: denominator / divisor,
  };
}

function addRational(a, b) {
  return rational(
    a.numerator * b.denominator +
    b.numerator * a.denominator,
    a.denominator * b.denominator,
  );
}

function subtractRational(a, b) {
  return rational(
    a.numerator * b.denominator -
    b.numerator * a.denominator,
    a.denominator * b.denominator,
  );
}

function invertRational(value) {
  if (value.numerator === 0n) {
    throw new RangeError("cannot invert zero");
  }

  return rational(
    value.denominator,
    value.numerator,
  );
}

function floorPositiveRational(value) {
  // 本函数只在非负区间中使用。
  return value.numerator / value.denominator;
}

function pow10(exponent) {
  if (
    !Number.isSafeInteger(exponent) ||
    exponent < 0
  ) {
    throw new RangeError(
      "decimal exponent is outside the supported range",
    );
  }

  return 10n ** BigInt(exponent);
}

function parseDecimalExactly(value) {
  const text = value.abs().valueOf();
  const match =
    /^(\d+)(?:\.(\d*))?(?:e([+-]?\d+))?$/i.exec(text);

  if (!match) {
    throw new TypeError(
      `cannot parse Decimal.js value: ${text}`,
    );
  }

  const integerPart = match[1];
  const fractionalPart = match[2] ?? "";
  const explicitExponent = Number(match[3] ?? 0);

  if (!Number.isSafeInteger(explicitExponent)) {
    throw new RangeError(
      "decimal exponent is outside the supported range",
    );
  }

  const allDigits = integerPart + fractionalPart;
  const firstNonZero = allDigits.search(/[1-9]/);

  if (firstNonZero < 0) {
    return {
      value: rational(0n),
      decimalExponent: 0,
    };
  }

  const scale =
    fractionalPart.length - explicitExponent;

  let numerator = BigInt(allDigits);
  let denominator = 1n;

  if (scale >= 0) {
    denominator = pow10(scale);
  } else {
    numerator *= pow10(-scale);
  }

  const decimalPointPosition =
    integerPart.length + explicitExponent;

  return {
    value: rational(numerator, denominator),
    decimalExponent:
      decimalPointPosition - firstNonZero - 1,
  };
}

function makeIntervalDelta(
  decimalExponent,
  intervalDigits,
) {
  const exponent =
    decimalExponent - intervalDigits;

  if (exponent >= 0) {
    return rational(4n * pow10(exponent));
  }

  return rational(4n, pow10(-exponent));
}

function reconstructContinuedFraction(coefficients) {
  let numeratorPrev2 = 0n;
  let numeratorPrev1 = 1n;
  let denominatorPrev2 = 1n;
  let denominatorPrev1 = 0n;

  for (const coefficient of coefficients) {
    const numerator =
      coefficient * numeratorPrev1 +
      numeratorPrev2;

    const denominator =
      coefficient * denominatorPrev1 +
      denominatorPrev2;

    numeratorPrev2 = numeratorPrev1;
    numeratorPrev1 = numerator;
    denominatorPrev2 = denominatorPrev1;
    denominatorPrev1 = denominator;
  }

  return rational(
    numeratorPrev1,
    denominatorPrev1,
  );
}

function simplestRationalInClosedInterval(
  lower,
  upper,
  maxDepth,
) {
  if (
    lower.numerator <= 0n ||
    upper.numerator <= 0n
  ) {
    return null;
  }

  const coefficients = [];
  let completed = false;

  // depth=0 是整数部分；ROM 的 21/29 上限针对
  // 后续连分数层，因此允许索引达到 maxDepth。
  for (
    let depth = 0;
    depth <= maxDepth;
    depth++
  ) {
    const lowerInteger =
      floorPositiveRational(lower);

    const upperInteger =
      floorPositiveRational(upper);

    // 下端点恰好为整数时，它就是该闭区间内
    // 最简单的有理数。
    if (
      lower.numerator % lower.denominator ===
      0n
    ) {
      coefficients.push(lowerInteger);
      completed = true;
      break;
    }

    if (lowerInteger !== upperInteger) {
      coefficients.push(lowerInteger + 1n);
      completed = true;
      break;
    }

    coefficients.push(lowerInteger);

    lower = subtractRational(
      lower,
      rational(lowerInteger),
    );

    upper = subtractRational(
      upper,
      rational(upperInteger),
    );

    if (lower.numerator === 0n) {
      completed = true;
      break;
    }

    // 0 < lower <= upper；取倒数后顺序反转。
    [lower, upper] = [
      invertRational(upper),
      invertRational(lower),
    ];
  }

  if (!completed) {
    return null;
  }

  return reconstructContinuedFraction(coefficients);
}

function bigintDigitCount(value) {
  return absBigInt(value).toString().length;
}

function fractionFitsCalculator(
  numerator,
  denominator,
  config,
) {
  const numeratorDigits =
    bigintDigitCount(numerator);

  const denominatorDigits =
    bigintDigitCount(denominator);

  return (
    numeratorDigits <=
    config.maxComponentDigits &&
    denominatorDigits <=
    config.maxComponentDigits &&
    numeratorDigits + denominatorDigits <=
    config.maxTotalFractionDigits
  );
}

/**
 *
 * @param {Decimal} value
 * @param {String} model
 * @return {Decimal[]|null}
 */
export function numberToFrac(
  value,
  model = "CY",
) {
  if (!Decimal.isDecimal(value)) {
    throw new TypeError(
      "value must be a Decimal.js object",
    );
  }

  const config = MODEL_CONFIGS[model];

  if (!config) {
    throw new RangeError(
      'model must be "CY" or "EY"',
    );
  }

  if (!value.isFinite() || value.isZero()) {
    return null;
  }

  const negative = value.isNegative();
  const parsed = parseDecimalExactly(value);

  const delta = makeIntervalDelta(
    parsed.decimalExponent,
    config.intervalDigits,
  );

  const lower = subtractRational(
    parsed.value,
    delta,
  );

  const upper = addRational(
    parsed.value,
    delta,
  );

  const candidate =
    simplestRationalInClosedInterval(
      lower,
      upper,
      config.maxContinuedFractionDepth,
    );

  if (
    candidate === null ||
    candidate.denominator === 1n
  ) {
    return null;
  }

  let numerator = candidate.numerator;
  const denominator = candidate.denominator;

  if (negative) {
    numerator = -numerator;
  }

  if (
    !fractionFitsCalculator(
      numerator,
      denominator,
      config,
    )
  ) {
    return null;
  }

  return [
    new Decimal(numerator.toString()),
    new Decimal(denominator.toString()),
  ];
}
